name: compchem

channels:
  - psi4/label/dev
  - conda-forge

dependencies:
  - python
  - numpy
  - rdkit
  - ipywidgets
  - widgetsnbextension
  - psi4
  - dftd3
  - scikit-learn
  - seaborn
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - py3Dmol

#  - pip:
#    - py3Dmol
#    - jupyterlab==1.1.4
#    - openchemistry==0.0.19
