name: compchem

channels:
  - psi4/label/dev
  - conda-forge
  - iwatobipen
  
dependencies:
  - python
  - numpy
  - scipy
  - rdkit
  - ipywidgets
  - widgetsnbextension
  - psi4
  - dftd3
  - scikit-learn
  - scikit-image
  - seaborn
  - debtcollector
  - psikit
  - resp
  - pip
  - pip:
    - nbgitpuller
    - sphinx-gallery
    - pandas
    - matplotlib
    - py3Dmol
    - pythreejs
    - fortecubeview
    - jupyterlab==1.1.4
    - openchemistry==0.0.19
